# Add 'calendar update' label to any PR where the head branch name starts with `dependabot/pip/exchange-calendars-`
'calendar update':
 - head-branch: ['^dependabot/pip/exchange-calendars-', 'dependabot/pip/exchange-calendars-']
